#!/usr/bin/env python3
"""
PNG to RGB565 Frame Converter for Claw Display
===============================================

Converts PNG sprite frames into C header files containing RGB565 pixel arrays
that the ESP32 firmware can display directly via LovyanGFX.

How it works:
  1. Reads each frame_NNN.png from the input directory
  2. Converts every pixel from 24-bit RGB to 16-bit RGB565 format
  3. Byte-swaps for little-endian storage (what the ESP32/GC9A01 expects)
  4. Writes one .h file per frame with a PROGMEM uint16_t array
  5. Generates a master frames.h that includes all frames and defines FRAME_COUNT

RGB565 format (16 bits per pixel):
  Bits: RRRRRGGG GGGBBBBB
  Red:   5 bits (0-31)
  Green: 6 bits (0-63)
  Blue:  5 bits (0-31)

Usage:
  python png_to_rgb565.py <input_dir> <output_dir>

Example:
  python tools/png_to_rgb565.py assets/frames firmware/include/frames

Input files must be named frame_000.png, frame_001.png, etc.
All PNGs should be 240x240 pixels with a black background.
"""

import sys
import os
from pathlib import Path

try:
    from PIL import Image
except ImportError:
    print("Error: Pillow is required. Install it with: pip install Pillow")
    sys.exit(1)

# Expected frame dimensions for the Waveshare ESP32-S3-LCD-1.28
EXPECTED_WIDTH = 240
EXPECTED_HEIGHT = 240


def rgb888_to_rgb565_le(r, g, b):
    """
    Convert a 24-bit RGB pixel to 16-bit RGB565, byte-swapped for little-endian.

    The GC9A01 display expects big-endian RGB565, but LovyanGFX's pushImage()
    with uint16_t arrays handles the byte order internally. We store as
    standard RGB565 (no manual byte swap needed when using pushImage with
    uint16_t arrays).

    Args:
        r: Red channel (0-255)
        g: Green channel (0-255)
        b: Blue channel (0-255)

    Returns:
        16-bit RGB565 value as an integer
    """
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def convert_frame(png_path, output_path, frame_name):
    """
    Convert a single PNG file to a C header with an RGB565 PROGMEM array.

    Args:
        png_path: Path to the input PNG file
        output_path: Path to write the output .h file
        frame_name: C identifier name for the array (e.g., "frame_000")
    """
    img = Image.open(png_path).convert("RGB")

    # Warn if dimensions don't match expected display size
    if img.size != (EXPECTED_WIDTH, EXPECTED_HEIGHT):
        print(f"  WARNING: {png_path.name} is {img.size[0]}x{img.size[1]}, "
              f"expected {EXPECTED_WIDTH}x{EXPECTED_HEIGHT}. "
              f"Image will be used as-is but may not display correctly.")

    width, height = img.size
    pixel_count = width * height

    # Convert all pixels to RGB565
    pixels = []
    for y in range(height):
        for x in range(width):
            r, g, b = img.getpixel((x, y))
            pixels.append(rgb888_to_rgb565_le(r, g, b))

    # Write C header file
    with open(output_path, "w") as f:
        f.write(f"// Auto-generated by png_to_rgb565.py from {png_path.name}\n")
        f.write(f"// {width}x{height} pixels, {pixel_count * 2} bytes\n")
        f.write(f"// DO NOT EDIT - regenerate with:\n")
        f.write(f"//   python tools/png_to_rgb565.py assets/frames firmware/include/frames\n\n")
        f.write(f"#pragma once\n")
        f.write(f"#include <pgmspace.h>\n\n")
        f.write(f"const uint16_t {frame_name}[{pixel_count}] PROGMEM = {{\n")

        # Write 12 values per line for readability
        for i in range(0, len(pixels), 12):
            chunk = pixels[i:i + 12]
            line = ", ".join(f"0x{p:04X}" for p in chunk)
            f.write(f"    {line},\n")

        f.write(f"}};\n")

    size_kb = (pixel_count * 2) / 1024
    print(f"  {png_path.name} -> {output_path.name} ({pixel_count} pixels, {size_kb:.1f} KB)")


def generate_master_header(output_dir, frame_names):
    """
    Generate the master frames.h that includes all individual frame headers
    and provides the FRAMES array and FRAME_COUNT constant.

    Args:
        output_dir: Directory to write frames.h into
        frame_names: List of frame C identifier names in order
    """
    master_path = output_dir / "frames.h"

    with open(master_path, "w") as f:
        f.write("// Auto-generated master frame header\n")
        f.write("// DO NOT EDIT - regenerate with:\n")
        f.write("//   python tools/png_to_rgb565.py assets/frames firmware/include/frames\n\n")
        f.write("#pragma once\n\n")

        # Include each frame header
        for name in frame_names:
            f.write(f'#include "{name}.h"\n')

        f.write(f"\n// Total number of animation frames\n")
        f.write(f"#define FRAME_COUNT {len(frame_names)}\n\n")

        # Array of pointers to each frame's pixel data
        f.write("// Array of frame pointers for sequential playback\n")
        f.write("const uint16_t* const FRAMES[] PROGMEM = {\n")
        for name in frame_names:
            f.write(f"    {name},\n")
        f.write("};\n")

    print(f"\n  Master header: {master_path.name} ({len(frame_names)} frames)")


def main():
    import argparse
    parser = argparse.ArgumentParser(description="Convert PNG frames to RGB565 C headers")
    parser.add_argument("input_dir", help="Directory containing frame_000.png, frame_001.png, ...")
    parser.add_argument("output_dir", help="Directory to write .h files into")
    parser.add_argument("--prefix", default="", help="Prefix for C array names (e.g., 'octopus_' -> octopus_frame_000)")
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)
    prefix = args.prefix

    # Validate input directory exists
    if not input_dir.is_dir():
        print(f"Error: Input directory not found: {input_dir}")
        sys.exit(1)

    # Create output directory if needed
    output_dir.mkdir(parents=True, exist_ok=True)

    # Find all frame PNGs, sorted by name for consistent ordering
    pngs = sorted(input_dir.glob("frame_*.png"))
    if not pngs:
        print(f"Error: No frame_*.png files found in {input_dir}")
        print(f"  Files should be named: frame_000.png, frame_001.png, etc.")
        sys.exit(1)

    print(f"Converting {len(pngs)} frames from {input_dir} -> {output_dir}")
    if prefix:
        print(f"  Array name prefix: {prefix}")
    print()

    # Convert each frame
    frame_names = []
    for png_path in pngs:
        frame_name = f"{prefix}{png_path.stem}"  # e.g., "octopus_frame_000"
        header_path = output_dir / f"{png_path.stem}.h"
        convert_frame(png_path, header_path, frame_name)
        frame_names.append(frame_name)

    # Generate master header (skip if using prefix, since main frames.h is hand-managed)
    if not prefix:
        generate_master_header(output_dir, frame_names)

    # Summary
    total_bytes = len(frame_names) * EXPECTED_WIDTH * EXPECTED_HEIGHT * 2
    print(f"\n  Total frame data: {total_bytes / 1024:.1f} KB "
          f"({total_bytes / (1024 * 1024):.1f} MB of ~13 MB available flash)")
    print("  Done!")


if __name__ == "__main__":
    main()
